FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install torch --index-url https://download.pytorch.org/whl/cpu --no-cache-dir

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 10000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]
